<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="sv" xml:lang="sv"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Linnéa Emanuelsson">

<title>Rapport</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Rapport_files/libs/clipboard/clipboard.min.js"></script>
<script src="Rapport_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Rapport_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Rapport_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Rapport_files/libs/quarto-html/popper.min.js"></script>
<script src="Rapport_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Rapport_files/libs/quarto-html/anchor.min.js"></script>
<link href="Rapport_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Rapport_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Rapport_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Rapport_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Rapport_files/libs/bootstrap/bootstrap-4d7f0bce1131f3e5f9547cd857cfbfc8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Innehållsförteckning</h2>
   
  <ul>
  <li><a href="#syfte" id="toc-syfte" class="nav-link active" data-scroll-target="#syfte"><span class="header-section-number">1</span> Syfte</a></li>
  <li><a href="#metod" id="toc-metod" class="nav-link" data-scroll-target="#metod"><span class="header-section-number">2</span> Metod</a>
  <ul class="collapse">
  <li><a href="#dataförståelse" id="toc-dataförståelse" class="nav-link" data-scroll-target="#dataförståelse"><span class="header-section-number">2.1</span> Dataförståelse</a></li>
  <li><a href="#datastädning-och-förberedelse" id="toc-datastädning-och-förberedelse" class="nav-link" data-scroll-target="#datastädning-och-förberedelse"><span class="header-section-number">2.2</span> Datastädning och förberedelse</a>
  <ul class="collapse">
  <li><a href="#saknade-värden" id="toc-saknade-värden" class="nav-link" data-scroll-target="#saknade-värden"><span class="header-section-number">2.2.1</span> Saknade värden</a></li>
  <li><a href="#nya-variabler" id="toc-nya-variabler" class="nav-link" data-scroll-target="#nya-variabler"><span class="header-section-number">2.2.2</span> Nya variabler</a></li>
  </ul></li>
  <li><a href="#beskrivande-analys" id="toc-beskrivande-analys" class="nav-link" data-scroll-target="#beskrivande-analys"><span class="header-section-number">2.3</span> Beskrivande analys</a>
  <ul class="collapse">
  <li><a href="#numeriska-variabler" id="toc-numeriska-variabler" class="nav-link" data-scroll-target="#numeriska-variabler"><span class="header-section-number">2.3.1</span> Numeriska variabler</a></li>
  <li><a href="#kategoriska-variabler" id="toc-kategoriska-variabler" class="nav-link" data-scroll-target="#kategoriska-variabler"><span class="header-section-number">2.3.2</span> Kategoriska variabler</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#regressionsanalys" id="toc-regressionsanalys" class="nav-link" data-scroll-target="#regressionsanalys"><span class="header-section-number">3</span> Regressionsanalys</a>
  <ul class="collapse">
  <li><a href="#linjär-regressionsmodel" id="toc-linjär-regressionsmodel" class="nav-link" data-scroll-target="#linjär-regressionsmodel"><span class="header-section-number">3.0.1</span> Linjär regressionsmodel</a></li>
  <li><a href="#lasso-regressionsmodell" id="toc-lasso-regressionsmodell" class="nav-link" data-scroll-target="#lasso-regressionsmodell"><span class="header-section-number">3.0.2</span> Lasso regressionsmodell</a></li>
  <li><a href="#modelljämförelse" id="toc-modelljämförelse" class="nav-link" data-scroll-target="#modelljämförelse"><span class="header-section-number">3.0.3</span> Modelljämförelse</a></li>
  </ul></li>
  <li><a href="#resultat" id="toc-resultat" class="nav-link" data-scroll-target="#resultat"><span class="header-section-number">4</span> Resultat</a></li>
  <li><a href="#slutsatser" id="toc-slutsatser" class="nav-link" data-scroll-target="#slutsatser"><span class="header-section-number">5</span> Slutsatser</a></li>
  <li><a href="#begränsningar" id="toc-begränsningar" class="nav-link" data-scroll-target="#begränsningar"><span class="header-section-number">6</span> Begränsningar</a></li>
  <li><a href="#rekommendationer" id="toc-rekommendationer" class="nav-link" data-scroll-target="#rekommendationer"><span class="header-section-number">7</span> Rekommendationer</a></li>
  <li><a href="#självreflektion" id="toc-självreflektion" class="nav-link" data-scroll-target="#självreflektion"><span class="header-section-number">8</span> Självreflektion</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Rapport</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Författare</div>
    <div class="quarto-title-meta-contents">
             <p>Linnéa Emanuelsson </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="syfte" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Syfte</h1>
<p>Ett försäkringsbolag har beställt en analys av deras historiska kunddata i syfte att undersöka vilka variabler som påverkar försäkringskostnaderna mest. Målet är att utreda datan och genomföra en regressionsanalys som förhoppningsvis kan användas som beslutsstöd för framtida kunder.</p>
</section>
<section id="metod" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Metod</h1>
<section id="dataförståelse" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="dataförståelse"><span class="header-section-number">2.1</span> Dataförståelse</h2>
<p>Datasetet består av 1100 observationer och 14 variabler. Av dessa 14 variabler är hälften numeriska och den andra hälften kategoriska.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,100
Columns: 14
$ customer_id       &lt;chr&gt; "C100000", "C100001", "C100002", "C100003", "C100004…
$ age               &lt;dbl&gt; 48, 40, 50, 62, 39, 39, 63, 52, 36, 49, 36, 36, 45, …
$ sex               &lt;chr&gt; "female", "male", "female", "male", "female", "femal…
$ region            &lt;chr&gt; "east", "west", "south", "north", "east", "west", "e…
$ bmi               &lt;dbl&gt; 24.8, 29.5, 18.3, 25.5, 27.3, 23.3, 23.9, 24.8, 28.6…
$ children          &lt;dbl&gt; 0, 1, 2, 5, 2, 4, 3, 2, 0, 2, 2, 2, 1, 1, 1, 1, 0, 3…
$ smoker            &lt;chr&gt; "no", "no", "no", "yes", "no", "no", "no", "no", "no…
$ chronic_condition &lt;chr&gt; "no", "no", "no", "no", "no", "no", "no", "no", "yes…
$ exercise_level    &lt;chr&gt; "high", "medium", "high", "medium", "medium", "high"…
$ plan_type         &lt;chr&gt; "basic", "basic", "standard", "basic", "basic", "sta…
$ prior_accidents   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0…
$ prior_claims      &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 3, 0, 0, 0…
$ annual_checkups   &lt;dbl&gt; 1, 4, 3, NA, 0, 2, 1, 2, 3, 2, 3, 3, 4, 4, 2, 1, 2, …
$ charges           &lt;dbl&gt; 6439.10, 8274.06, 5190.99, 14500.35, 6534.40, 8026.3…</code></pre>
</div>
</div>
</section>
<section id="datastädning-och-förberedelse" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="datastädning-och-förberedelse"><span class="header-section-number">2.2</span> Datastädning och förberedelse</h2>
<section id="saknade-värden" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="saknade-värden"><span class="header-section-number">2.2.1</span> Saknade värden</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 69 × 14
   customer_id   age sex    region   bmi children smoker chronic_condition
   &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;            
 1 C100003        62 male   north   25.5        5 yes    no               
 2 C100016        29 male   north   NA          0 no     no               
 3 C100027        47 male   south   NA          4 no     yes              
 4 C100057        38 male   east    NA          0 no     yes              
 5 C100084        31 female south   22.9        3 no     no               
 6 C100088        35 female west    32.4        0 no     no               
 7 C100138        53 male   east    32.7        0 no     yes              
 8 C100183        48 female south   24.2        3 no     yes              
 9 C100190        36 female west    NA          1 no     no               
10 C100199        27 female south   NA          1 no     no               
# ℹ 59 more rows
# ℹ 6 more variables: exercise_level &lt;chr&gt;, plan_type &lt;chr&gt;,
#   prior_accidents &lt;dbl&gt;, prior_claims &lt;dbl&gt;, annual_checkups &lt;dbl&gt;,
#   charges &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Datasetet har 3 kolumner med saknade värden: exercise_level (22) som är kategorisk, samt två numeriska variabler: annual_checkups(20)och bmi(28). Med tanke på att datasetet inte är så stort (består av 1100 observationer och 14 variabler) och att antalen saknade värdena är så få så lades prio på att ha kvar dem raderna vi kunde. Dem numeriska saknade värdena hanterades genom att inputera medianen av värdena, medan dem kategoriska (exercise_level) hanterades genom att skapa en egen kategori för saknade värden = missing.</p>
</section>
<section id="nya-variabler" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="nya-variabler"><span class="header-section-number">2.2.2</span> Nya variabler</h3>
<p>2 nya variabler skapades - det tillåter en lättare jämförelse mellan grupper och prissättningen, det ger en tydligare beskrivning när man jämför relationer, jobbar med regressionsmodeller samt för att se skillnaden mellan dem olika grupperna i visualiseringarna. - bmi_group - skillnaden mellan min och max värdet av bmi användes för att sedan dela upp siffrorna i 3 lika kategorier: lower(17-26), average(27-35) &amp; higher(36-44) - age_group - här använde jag mig av age och delade upp siffrorna i klassiska åldersgrupper för att lättare kunna identifiera trender mellan grupper med liknande situationer - youth(18-24), adult(25-59), senior(60+)</p>
</section>
</section>
<section id="beskrivande-analys" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="beskrivande-analys"><span class="header-section-number">2.3</span> Beskrivande analys</h2>
<p>Med tanke på att vi har flera variabler att jämföra så har jag delat upp analysen i numeriska och kategoriska variabler:</p>
<section id="numeriska-variabler" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="numeriska-variabler"><span class="header-section-number">2.3.1</span> Numeriska variabler</h3>
<p>Dem numeriska variablerna (age,bmi,children,prior_accidents,prior_claims,annual_checkups) jämfördes i en korrelations heatmap mot charges för att utreda vilka variabler hade starkast relation till försäkringskostnaderna (<a href="#fig-heatmap" class="quarto-xref">Figur&nbsp;1</a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-heatmap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Rapport_files/figure-html/fig-heatmap-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figur&nbsp;1: Numerical predictors heatmap.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Heatmappen visar att dem numeriska variablerna med högst korrelation till charges är age( 0.26), prior_accidents (0.24) och prior_claims (0.18). Det betyder att dessa 3 variabler borde inkluderas i en prediktiv model även om korrelationerna inte är väldigt höga (ligger under 0.5), vilket kan innebära att korrelationen blir starkare ihop med visa kategoriska variabler.</p>
</section>
<section id="kategoriska-variabler" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="kategoriska-variabler"><span class="header-section-number">2.3.2</span> Kategoriska variabler</h3>
<p>För kategoriska variabler (sex, region, smoker, chronic_condition, exercise_level, plan_type, bmi_group, age_group)skapades en funktion som kalkylerade varje prediktors relatiion charges genomsnitt, median och standard deviation samt skapade en boxplot som visade relationen. Rankning på dem starkaste kategoriska prediktorerna är smoker på första plats, följt av chronic_condition. Sedan har vi andra ganska starka prediktorer som exercise_level, age_group och plan_type. Med tanke på att dem kategoriska variablerna var så tydligt starkare än dem numeriska, valde jag att gå vidare med följande: smoker, chronic_condition, exercise_level, age_group och plan_type.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rapport_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="regressionsanalys" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Regressionsanalys</h1>
<section id="linjär-regressionsmodel" class="level3" data-number="3.0.1">
<h3 data-number="3.0.1" class="anchored" data-anchor-id="linjär-regressionsmodel"><span class="header-section-number">3.0.1</span> Linjär regressionsmodel</h3>
<p>Jag började med en linjär regressionsmodell av dem 5 starkaste prediktorerna jag hade hittat: smoker, chronic_condition, exercise_level, age_group och plan_type.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ smoker + chronic_condition + exercise_level + 
    prior_accidents + prior_claims + plan_type, data = ready_data[train_index, 
    ])

Residuals:
    Min      1Q  Median      3Q     Max 
-9290.9 -1728.0   -82.8  1529.2 16851.9 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             5618.8      253.1  22.198  &lt; 2e-16 ***
smokerTRUE              7472.2      241.1  30.998  &lt; 2e-16 ***
chronic_conditionTRUE   4022.2      208.7  19.270  &lt; 2e-16 ***
exercise_levellow       1990.9      270.6   7.358 4.33e-13 ***
exercise_levelmedium     839.0      240.8   3.484 0.000518 ***
exercise_levelmissing   1109.2      660.5   1.679 0.093447 .  
prior_accidents         1232.1      186.5   6.606 6.86e-11 ***
prior_claims             800.8      172.1   4.652 3.80e-06 ***
plan_typePremium        1476.5      265.8   5.554 3.70e-08 ***
plan_typeStandard        625.6      206.8   3.025 0.002560 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2651 on 870 degrees of freedom
Multiple R-squared:  0.679, Adjusted R-squared:  0.6757 
F-statistic: 204.5 on 9 and 870 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Smoker och chronic_condition har dem högsta koefficienterna av dem 5 prediktorerna som valdes ut. Multiple R-squared ligger på 0.68 vilket skulle kunna förbättras, så med tanke på det och i syfte att se att ingen annan prediktor missats skapade jag en andra linjär regression med alla variabler.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = charges ~ age + sex + region + bmi + children + 
    smoker + chronic_condition + exercise_level + plan_type + 
    prior_accidents + prior_claims + annual_checkups + age_group + 
    bmi_group, data = ready_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-8915.9 -1495.2  -103.4  1345.7 17483.0 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           -1548.52     974.91  -1.588  0.11250    
age                      64.76       8.86   7.310 5.21e-13 ***
sexmale                -171.03     140.52  -1.217  0.22384    
regionNorth              72.11     205.31   0.351  0.72548    
regionSouth             298.60     196.40   1.520  0.12872    
regionWest              210.02     205.68   1.021  0.30744    
bmi                     161.10      29.80   5.405 7.96e-08 ***
children                 75.43      47.68   1.582  0.11392    
smokerTRUE             7421.96     182.95  40.568  &lt; 2e-16 ***
chronic_conditionTRUE  3836.26     167.57  22.894  &lt; 2e-16 ***
exercise_levellow      1486.95     210.69   7.057 3.03e-12 ***
exercise_levelmedium    514.55     189.25   2.719  0.00666 ** 
exercise_levelmissing   753.32     523.05   1.440  0.15009    
plan_typePremium       1533.58     207.74   7.382 3.11e-13 ***
plan_typeStandard       704.15     160.92   4.376 1.33e-05 ***
prior_accidents        1040.03     143.85   7.230 9.14e-13 ***
prior_claims            881.67     136.54   6.457 1.61e-10 ***
annual_checkups          -4.37      61.74  -0.071  0.94358    
age_groupsenior         465.71     313.51   1.485  0.13771    
age_groupyouth          208.53     317.95   0.656  0.51205    
bmi_grouphigher         370.74     391.61   0.947  0.34400    
bmi_grouplower          112.05     251.37   0.446  0.65587    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2313 on 1078 degrees of freedom
Multiple R-squared:  0.7492,    Adjusted R-squared:  0.7443 
F-statistic: 153.4 on 21 and 1078 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Residual standard error har nu gått ner från 2594 till 2313 vilket visar på att tillagda variabler ger lite mer precision i beräkningarna inte bara noise. Multiple R-squared har nu gått upp från 0.68 till 0.75 vilket innebär att modellen är något starkare än i första versionen. Koefficienterna visar liknande trender som tidigare - rökare med kronisk sjukdom, som inte tränar mycket och har premium paket betalar högst. En variabel som inte visade sig ha lika stor betydelse som trott är age_group. Istället visade sig 2 andra prediktorer ha högre påverkan på charges: prior_accidents och prior_claims. Detta ändrade mitt perspektiv om vilka dem topp prediktorerna egentligen var - så jag ändrade det från smoker, chronic_condition, exercise_level, age_group och plan_type till smoker, chronic_condition, exercise_level, prior_accidents, prior_claims och plan_type i en ny modell.</p>
</section>
<section id="lasso-regressionsmodell" class="level3" data-number="3.0.2">
<h3 data-number="3.0.2" class="anchored" data-anchor-id="lasso-regressionsmodell"><span class="header-section-number">3.0.2</span> Lasso regressionsmodell</h3>
<p>Den första modellen - linjär regression är enkel och lätt att tolka som modell men den har hög risk för overfitting samt att den inte hanterar multikollinearitet väl. För att inte riskera att missa dessa faktorer så valde jag att testa ytterligare regressionsmodeller - lasso regression, som valdes för att: - Lasso krymper orelevanta koefficienter till noll - Bra på att identifiera starkaste prediktorer - Bättre på att identifiera när variabler är korrelerade än linjär regression.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          Length Class     Mode   
a0          71   -none-    numeric
beta      1491   dgCMatrix S4     
df          71   -none-    numeric
dim          2   -none-    numeric
lambda      71   -none-    numeric
dev.ratio   71   -none-    numeric
nulldev      1   -none-    numeric
npasses      1   -none-    numeric
jerr         1   -none-    numeric
offset       1   -none-    logical
call         4   -none-    call   
nobs         1   -none-    numeric</code></pre>
</div>
</div>
</section>
<section id="modelljämförelse" class="level3" data-number="3.0.3">
<h3 data-number="3.0.3" class="anchored" data-anchor-id="modelljämförelse"><span class="header-section-number">3.0.3</span> Modelljämförelse</h3>
<p>Målet är att välja en regressionsmodell som kan användas som stöd vid framtida prissättning med liknande kunder. Med det i åtanke ville jag nu testa dem fyra modellernas prediktionsförmåga genom att dela upp datan i test och train set och sedan jämföra RMSE, MAE &amp; R2.</p>
</section>
</section>
<section id="resultat" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Resultat</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  model                     RMSE   MAE R_squared
  &lt;chr&gt;                    &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
1 Linjär (top prediktorer) 2260. 1796.     0.715
2 Linjär (alla variabler)  2116. 1688.     0.750
3 Lasso (top prediktorer)  2258. 1795.     0.716
4 Lasso (alla variabler)   2112. 1695.     0.751</code></pre>
</div>
</div>
<p>När man jämför dem linjära och lasso modellerna är skillnaderna försumbara.Detta betyder att datasetet är stabilt och att korrelationerna mellan variablerna inte var så komplexa att dem inte kunde fångas up av en linjär regressionsmodell. Anledningen kan vara att vi inte har så många variabler och att korrelationerna mellan dem inte är så komplexa. Resultaten visar att dem fulla modellerna med alla prediktorer presterar bättre än fokusmodellerna vilket är fullt rimligt. Fokusvariablerna som valdes gav omkring 71.5% av variationen i charges vilket är ganska bra, när man tänker på att i modellerna med fulla variabler så var resultatet 75%. Det visar att fokus prediktorerna som valdes var dem som hade högst påverkan på försäkringskostnaden.</p>
</section>
<section id="slutsatser" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Slutsatser</h1>
<p>Dem starkaste prediktorerna av försäkringskostnader var smoker, chronic_condition, exercise_level, prior_accidents, prior_claims och plan_type. Detta bekräftades av både graferna (boxplots och heatmap) samt av regressionsmodellerna. Sammantaget pekar resultaten på att livsstilsfaktorer (som rökning och träningsnivå), medicinska faktorer (chronic_condition) och tidigare skadehistorik är centrala drivkrafter bakom försäkringskostnaderna.</p>
</section>
<section id="begränsningar" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Begränsningar</h1>
<p>För att börja med så var datasetet relativt litet så skulle behöva utökas med fler observationer samt mer variabler för en bättre helhetsbild - vi skulle kunna få in faktorer som inkomst, utbildningsnivå, etc. Vi hade 2 kolumner med saknade värden som hanterades genom att inputera medianen vilket i situationen är rimligt men kan påverka precision. Den tredje kolumnen som saknade värden hanterades genom att skapa en ny kategori - “Missing” så vi kunde ha kvar observationerna. Än en gång - rimlig lösning men svårt att analysera datan i efterhand. 2 nya variabler skapades - bmi_group som baserades på att dela upp siffrorna lika i 3 grupper (lower, average, higher) och age_group som baserade sig på klassiska åldersgrupper som använts i hälsostudier (youth, adult, senior). Dessa grupperingar underlättar analys men kan förenkla verkligheten såpass att den döljer variationer inom grupperna. Linjär regressionsmodellen förutsätter linjära samband, normalfördelade residualer och homogen varians. Den har hög risk för overfitting samt att den inte hanterar multikollinearitet väl. Ett alternativ var då att använda mig av lasso-modellen men den är känslig för skalning och korrelation vilket kan innebära att starkt korrelerade prediktorer påverkar vilka variabler som väljs bort.</p>
</section>
<section id="rekommendationer" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Rekommendationer</h1>
<p>Nästa steg i projektet skulle kunna vara att samla in fler relevanta variabler som nämndes innan samt att utöka antalet observationer. Man skulle även kunna testa datan på icke-linjära modeller som Random Forest för att fånga komplexa samband vilket annars kan missas. I samma veva skulle man även kunna validera modellen på ett helt nytt dataset för att se om overfitting var ett problem. Ett möjligt fokusområde kunde vara att undersöka interaktionseffekter mellan olika variabler för potentiellt viktiga insikter i kundbefolkningen. Exempelvis relationen mellan rökare och träningsnivå eller ålder och bmi.</p>
</section>
<section id="självreflektion" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Självreflektion</h1>
<p>Projektet var kul men jag kände mig lite osäker hur man bäst analyserade alla möjliga prediktorer så min beskrivande analys kan absolut förbättras vilket påvisades i regressionsanalys delen där jag märkte att jag valt fel prediktorer att fokusera på. Den här delen tyckte jag var svårast speciellt med skillnaderna i hur man kan analysera numeriska och kategoriska variabler. Själva regressionanalys delen tyckte jag var kul och ville testa lite olika modeller för att se om jag kunde få ett bättre resultat genom lasso regression. Jag tror jag har uppfyllt kraven för VG genom att analysera dem olika modellerna, dess styrkor och svagheter samt testa alternativ för att se om jag kunde hitta något annorlunda.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopierat!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopierat!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>